### Task 11: NumPy advanced operations (indexing, slicing, broadcasting)
#### Submitted by: Awais Anwer

#### Indexing and Slicing

In [2]:
# Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).
# From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.
# Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].
# Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].
# From a 1D array of random integers, extract all elements that are greater than 8.
# Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.

In [3]:
import numpy as np

In [4]:
# Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).
arr = np.arange(36).reshape(6, 6)
sub_array = arr[1:3, 1:3]
print(sub_array)

[[ 7  8]
 [13 14]]


In [5]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [6]:
# From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.
arr = np.arange(6).reshape(3, 2, 1)
print("3D Array:")
print(arr)

sub_arr = arr[1, :, :]
print("\nSub Array: ")
print(sub_arr)

3D Array:
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]

Sub Array: 
[[2]
 [3]]


In [7]:
# Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = [1, 3, 4, 6]
print(arr[indices])

[2 4 5 7]


In [8]:
# Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].
arr = np.arange(12).reshape(3, 4)
rows = np.array([0, 2, 2])
cols = np.array([1, 3])
print("Actual 2D array:")
print(arr)
print("\nSub array:")
print(arr[rows[:, np.newaxis], cols])

Actual 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sub array:
[[ 1  3]
 [ 9 11]
 [ 9 11]]


In [13]:
# From a 1D array of random integers, extract all elements that are greater than 8.
arr = np.random.randint(20, size=20)
print("Original array:")
print(arr)
print("\nElements greater than 8:")
print(arr[arr > 8])

Original array:
[16  3 16 11  1 19  8 16 16 16  3  6 17  6 11 16 19 16 10  7]

Elements greater than 8:
[16 16 11 19 16 16 16 17 11 16 19 16 10]


In [14]:
# Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.
arr = np.arange(36).reshape(6, 6)
print("Original array:")
print(arr)
print("\nModified array:")
arr[arr > 13] = 0
print(arr)

Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Modified array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


### Broadcasting

In [15]:
# Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).
# Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)
# Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.
# Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [16]:
# Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).
one_d_array = np.array([1, 2, 3])
two_d_array = np.arange(12).reshape(4, 3)
print("Original 1D array:")
print(one_d_array)
print("\nOriginal 2D array:")
print(two_d_array)
print("\nAdded 1D array to each row of 2D array:")
print(two_d_array + one_d_array)

Original 1D array:
[1 2 3]

Original 2D array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Added 1D array to each row of 2D array:
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


In [22]:
# Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,)
two_d_array = np.arange(9).reshape(3, 3)
one_d_array = np.array([1, 2, 3])
result = np.dot(two_d_array, one_d_array)
print(result)

[ 8 26 44]


In [25]:
# Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.
array1 = np.arange(3).reshape(3, 1)
array2 = np.arange(4).reshape(1, 4)
print("\narray 1:")
print(array1)
print("\narray 2:")
print(array2)
print("\nElement-wise addition:")
result = array1 + array2
print(result)


array 1:
[[0]
 [1]
 [2]]

array 2:
[[0 1 2 3]]

Element-wise addition:
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [26]:
# Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.
three_d_array = np.arange(24).reshape(2, 3, 4)
two_d_array = np.arange(12).reshape(3, 4)
print("Original 3D array:")
print(three_d_array)
print("\nOriginal 2D array:")
print(two_d_array)
print("\nAdded 2D array to each 2D slice along the first axis:")
result = three_d_array + two_d_array
print(result)

Original 3D array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Original 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Added 2D array to each 2D slice along the first axis:
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]


### See More

In [27]:
# Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.
# From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.
# Given a 2D array, extract the diagonal elements and create a 1D array.
# Use slicing to reverse the order of elements in each row of a 2D array.
# Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.
# Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [33]:
# Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.
two_d_array = np.arange(12).reshape(3, 4)
print("Original 2D array:")
print(two_d_array)
sliced_array = two_d_array[::2, ::2]
print("\nSliced array:")
print(sliced_array)
one_d_array = np.array([3, 4])
print("\n1D array:")
print(one_d_array)
result = sliced_array + one_d_array
print("\nResult:")
print(result)

Original 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sliced array:
[[ 0  2]
 [ 8 10]]

1D array:
[3 4]

Result:
[[ 3  6]
 [11 14]]


In [37]:
# From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.
three_d_array = np.arange(6).reshape(3, 2, 1)
print("Original 3D array:")
print(three_d_array)
sliced_array = three_d_array[:, :, :1]
print("\nSliced array:")
print(sliced_array)

two_d_array = np.arange(4).reshape(2, 2)
print("\n2D array:")
print(two_d_array)
result = sliced_array - two_d_array
print("\nResult:")
print(result)

Original 3D array:
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]

Sliced array:
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]

2D array:
[[0 1]
 [2 3]]

Result:
[[[ 0 -1]
  [-1 -2]]

 [[ 2  1]
  [ 1  0]]

 [[ 4  3]
  [ 3  2]]]


In [39]:
# Given a 2D array, extract the diagonal elements and create a 1D array.
two_d_array = np.arange(9).reshape(3, 3)
print("Original 2D array:")
print(two_d_array)
print("\nDiagonal elements:")
diagonal_array = np.diag(two_d_array)
print(diagonal_array)

Original 2D array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Diagonal elements:
[0 4 8]


In [43]:
# Use slicing to reverse the order of elements in each row of a 2D array.
two_d_array = np.arange(12).reshape(3, 4)
print("Original 2D array:")
print(two_d_array)
print("\nReversed array:")
reversed_array = two_d_array[:, ::-1]
print(reversed_array)

Original 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reversed array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [44]:
# Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.
three_d_array = np.random.randint(10, size=(7, 6, 5))
print("Original 3D array:")
print(three_d_array)
sliced_array = three_d_array[:2, :3, :4]
print("\nSliced array:")
print(sliced_array)

one_d_array = np.arange(4)
print("\n1D array:")
print(one_d_array)
result = sliced_array + one_d_array
print("\nResult:")
print(result)

Original 3D array:
[[[7 4 8 5 3]
  [4 6 0 9 7]
  [1 1 6 3 8]
  [5 1 7 3 9]
  [9 8 3 0 6]
  [0 9 5 7 8]]

 [[8 2 7 3 7]
  [3 4 0 0 9]
  [9 7 8 8 4]
  [4 1 4 5 0]
  [9 9 2 9 9]
  [1 4 2 9 4]]

 [[2 8 7 6 6]
  [3 9 6 9 9]
  [7 1 6 0 9]
  [2 6 6 4 6]
  [2 0 8 0 0]
  [3 9 3 9 4]]

 [[4 1 7 6 6]
  [5 3 5 5 3]
  [7 9 0 5 8]
  [4 9 9 7 8]
  [4 4 6 8 3]
  [3 5 8 7 1]]

 [[2 3 5 5 1]
  [6 1 6 1 3]
  [2 8 6 5 4]
  [3 4 2 0 0]
  [8 3 6 8 9]
  [4 1 3 9 1]]

 [[7 1 9 8 4]
  [5 8 0 7 2]
  [9 0 7 7 9]
  [2 5 0 7 8]
  [5 9 4 9 7]
  [5 3 0 1 5]]

 [[3 4 0 3 5]
  [5 3 6 3 4]
  [0 9 3 4 1]
  [0 9 2 8 0]
  [7 3 7 7 3]
  [7 2 9 0 1]]]

Sliced array:
[[[7 4 8 5]
  [4 6 0 9]
  [1 1 6 3]]

 [[8 2 7 3]
  [3 4 0 0]
  [9 7 8 8]]]

1D array:
[0 1 2 3]

Result:
[[[ 7  5 10  8]
  [ 4  7  2 12]
  [ 1  2  8  6]]

 [[ 8  3  9  6]
  [ 3  5  2  3]
  [ 9  8 10 11]]]


In [47]:
# Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.
two_d_array = np.random.randint(10, size=(3, 4))
print("Original 2D array:")
print(two_d_array)
print("\nLast column set to sum of first two columns:")
two_d_array[:, -1] = two_d_array[:, 0] + two_d_array[:, 1]
print(two_d_array)

Original 2D array:
[[6 3 5 2]
 [5 4 0 2]
 [5 5 0 8]]

Last column set to sum of first two columns:
[[ 6  3  5  9]
 [ 5  4  0  9]
 [ 5  5  0 10]]
