# Task 21: Linear algebra and Calculus in NumPy
Submitted by: Awais Anwer

## Linear Algebra Tasks

In [2]:
import numpy as np

### 1. Matrix Creation and Manipulation

In [3]:
# Create various types of matrices (zero matrix, identity matrix, random matrix).
# Perform basic matrix operations (addition, subtraction, multiplication).
# Transpose a matrix and find the determinant and inverse of a matrix.

In [4]:
# zero matrix
zero_matrix = np.zeros((3, 3), dtype=int)
print("Zero Matrix:")
print(zero_matrix)

Zero Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# Identity Matrix
identity_matrix = np.identity(3, dtype=int)
print("Identity Matrix:")
print(identity_matrix)

Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
# Random Matrix
np.random.seed(42)
random_matrix = np.random.randint(1, 10, size=(3, 3), dtype=int)
print("Random Matrix:")
print(random_matrix)

Random Matrix:
[[7 4 8]
 [5 7 3]
 [7 8 5]]


In [7]:
# addition
addition_matrix = identity_matrix + random_matrix
print("Addition Matrix:")
print(addition_matrix)

Addition Matrix:
[[8 4 8]
 [5 8 3]
 [7 8 6]]


In [8]:
# subtraction
subtraction_matrix = random_matrix - identity_matrix
print("Subtraction Matrix:")
print(subtraction_matrix)

Subtraction Matrix:
[[6 4 8]
 [5 6 3]
 [7 8 4]]


In [9]:
# multiplication
multiplication_matrix = np.dot(identity_matrix, random_matrix)
print("Multiplication Matrix:")
print(multiplication_matrix)

Multiplication Matrix:
[[7 4 8]
 [5 7 3]
 [7 8 5]]


In [10]:
# transpose of random matrix
transpose_matrix = np.transpose(random_matrix)
print("Random Matrix:")
print(random_matrix)
print("\nTranspose Matrix:")
print(transpose_matrix)

Random Matrix:
[[7 4 8]
 [5 7 3]
 [7 8 5]]

Transpose Matrix:
[[7 5 7]
 [4 7 8]
 [8 3 5]]


In [11]:
# determinant of random matrix
determinant = np.linalg.det(random_matrix)

print("Random Matrix:")
print(random_matrix)

print("\nDeterminant of Random Matrix:")
print(determinant)

Random Matrix:
[[7 4 8]
 [5 7 3]
 [7 8 5]]

Determinant of Random Matrix:
-11.00000000000003


In [12]:
# inverse of random matrix
inverse_matrix = np.linalg.inv(random_matrix)

print("Random Matrix:")
print(random_matrix)

print("\nInverse of Random Matrix:")
print(inverse_matrix)

Random Matrix:
[[7 4 8]
 [5 7 3]
 [7 8 5]]

Inverse of Random Matrix:
[[-1.         -4.          4.        ]
 [ 0.36363636  1.90909091 -1.72727273]
 [ 0.81818182  2.54545455 -2.63636364]]


### 2. Solving Linear Equations

In [13]:
# Use NumPy to solve a system of linear equations.
# Implement matrix factorization methods (LU decomposition, QR decomposition).

In [14]:
# Use NumPy to solve a system of linear equations.
A = np.array([[2, 3], [1, -1]])
B = np.array([5, 2])

X = np.linalg.solve(A, B)

print("Coefficient Matrix:")
print(A)

print("\nOrdinates:")
print(B)

print("\nSolution:")
print(X)

Coefficient Matrix:
[[ 2  3]
 [ 1 -1]]

Ordinates:
[5 2]

Solution:
[2.2 0.2]


In [15]:
# Implement matrix factorization methods (LU decomposition, QR decomposition).
# LU decomposition
from scipy.linalg import lu
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
P, L, U = lu(A)

print("A:\n", A)
print()
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

A:
 [[2 1 1]
 [1 3 2]
 [1 0 0]]

P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L:
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
U:
 [[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


In [16]:
# QR decomposition
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
Q, R = np.linalg.qr(A)

print("A:\n", A)
print()
print("Q:\n", Q)
print("R:\n", R)

A:
 [[2 1 1]
 [1 3 2]
 [1 0 0]]

Q:
 [[-0.81649658  0.27602622 -0.50709255]
 [-0.40824829 -0.89708523  0.16903085]
 [-0.40824829  0.34503278  0.84515425]]
R:
 [[-2.44948974 -2.04124145 -1.63299316]
 [ 0.         -2.41522946 -1.51814423]
 [ 0.          0.         -0.16903085]]


### 3. Eigenvalues and Eigenvectors

In [17]:
# Calculate the eigenvalues and eigenvectors of a given matrix.
# Verify the results by reconstructing the original matrix.

In [18]:
# Calculate the eigenvalues and eigenvectors of a given matrix.
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("A:\n", A)
print()
print("Eigenvalues:\n", eigenvalues)
print()
print("Eigenvectors:\n", eigenvectors)

A:
 [[2 1 1]
 [1 3 2]
 [1 0 0]]

Eigenvalues:
 [ 3.91222918  1.28646207 -0.19869124]

Eigenvectors:
 [[-0.51233387 -0.51118241 -0.17058945]
 [-0.84874276  0.76210326 -0.48349198]
 [-0.13095702 -0.39735522  0.85856551]]


In [19]:
# Verify the results by reconstructing the original matrix.
reconstructed_matrix = np.dot(np.dot(eigenvectors, np.diag(eigenvalues)), np.linalg.inv(eigenvectors))

print("Reconstructed Matrix:\n", reconstructed_matrix)

Reconstructed Matrix:
 [[ 2.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00 -5.01869369e-16 -4.60303188e-16]]


### 4. Vector Operations

In [20]:
# Perform basic vector operations (addition, dot product, cross product).
# Normalize a vector and compute vector norms.

In [21]:
# Perform basic vector operations (addition, dot product, cross product).
vector_a = np.array([1, 2, 3, 4, 3, 2, 8, 1])
vector_b = np.array([3, 3, 3, 3, 3, 3, 4, 4])

# addition
addition_result = vector_a + vector_b
print("Vector A:\n", vector_a)
print("Vector B:\n", vector_b)
print("Addition Result:\n", addition_result)

Vector A:
 [1 2 3 4 3 2 8 1]
Vector B:
 [3 3 3 3 3 3 4 4]
Addition Result:
 [ 4  5  6  7  6  5 12  5]


In [22]:
# dot product
dot_product_result = np.dot(vector_a, vector_b)

print("Vector A:\n", vector_a)
print("Vector B:\n", vector_b)
print("Dot Product Result:\n", dot_product_result)

Vector A:
 [1 2 3 4 3 2 8 1]
Vector B:
 [3 3 3 3 3 3 4 4]
Dot Product Result:
 81


### 5. Matrix Decompostion

In [23]:
# Understand and implement Principal Component Analysis (PCA) using SVD.
data = np.array([[2.5, 2.4],
                 [0.5, 0.7],
                 [2.2, 2.9],
                 [1.9, 2.2],
                 [3.1, 3.0],
                 [2.3, 2.7],
                 [2.0, 1.6],
                 [1.0, 1.1],
                 [1.5, 1.6],
                 [1.1, 0.9]])

In [24]:
print(data)

[[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]


In [25]:
num_components = 2

# Step 1: Standardize the data
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
standardized_data = (data - mean) / std

# Step 2: Compute the covariance matrix
covariance_matrix = np.cov(standardized_data, rowvar=False)

# Step 3: Perform SVD
U, S, Vt = np.linalg.svd(covariance_matrix)

# Step 4: Compute the principal components
principal_components = Vt[:num_components]

# Step 5: Transform the data
transformed_data = np.dot(standardized_data, principal_components.T)

In [26]:
print("Transformed Data:\n", transformed_data)
print("Principal Components:\n", principal_components)

Transformed Data:
 [[-1.08643242 -0.22352364]
 [ 2.3089372   0.17808082]
 [-1.24191895  0.501509  ]
 [-0.34078247  0.16991864]
 [-2.18429003 -0.26475825]
 [-1.16073946  0.23048082]
 [ 0.09260467 -0.45331721]
 [ 1.48210777  0.05566672]
 [ 0.56722643  0.02130455]
 [ 1.56328726 -0.21536146]]
Principal Components:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


# Calculus Tasks

### 1. Numerical Differentiation


In [27]:
# Use NumPy to compute the numerical derivative of a given function.
# Implement forward, backward, and central difference methods for differentiation.

In [33]:
polynomial_function = np.poly1d([3, 2, 1])
print("Polynomial function f(x):\n", polynomial_function)

Polynomial function f(x):
    2
3 x + 2 x + 1


In [35]:
derivative = polynomial_function.deriv()
print("Derivative of the polynomial function:\n", derivative)

Derivative of the polynomial function:
  
6 x + 2


In [36]:
print(derivative(5))

32


In [42]:
def forward_difference(f, x, h):
    return (f(x + h) - f(x)) / h

def backward_difference(f, x, h):
    return (f(x) - f(x - h)) / h

def central_difference(f, x, h):
    return (f(x + h) - f(x - h)) / (2 * h)

In [46]:
# Example usage
x = np.linspace(-10, 10, 100)
h = 1e-5

f = lambda x: polynomial_function(x)

forward_diff = forward_difference(f, x, h)
backward_diff = backward_difference(f, x, h)
central_diff = central_difference(f, x, h)

true_derivative = derivative(x)

# Print results for comparison
print("\nForward Difference:\n", forward_diff)
print("\nBackward Difference:\n", backward_diff)
print("\nCentral Difference:\n", central_diff)
print("\nTrue Derivative (symbolic):\n", true_derivative)


Forward Difference:
 [-57.99997    -56.78784878 -55.57572757 -54.36360636 -53.15148515
 -51.93936394 -50.72724272 -49.51512151 -48.3030003  -47.09087909
 -45.87875788 -44.66663667 -43.45451545 -42.24239424 -41.03027303
 -39.81815182 -38.6060306  -37.39390939 -36.18178818 -34.96966697
 -33.75754576 -32.54542454 -31.33330333 -30.12118212 -28.90906091
 -27.6969397  -26.48481848 -25.27269727 -24.06057606 -22.84845485
 -21.63633364 -20.42421242 -19.21209121 -17.99997    -16.78784879
 -15.57572758 -14.36360636 -13.15148515 -11.93936394 -10.72724273
  -9.51512152  -8.3030003   -7.09087909  -5.87875788  -4.66663667
  -3.45451545  -2.24239424  -1.03027303   0.18184818   1.39396939
   2.60609061   3.81821182   5.03033303   6.24245424   7.45457545
   8.66669667   9.87881788  11.09093909  12.3030603   13.51518152
  14.72730273  15.93942394  17.15154515  18.36366636  19.57578758
  20.78790879  22.00003     23.21215121  24.42427242  25.63639364
  26.84851485  28.06063606  29.27275727  30.48487848  

### 2. Numerical Integration

In [47]:
# Use NumPy to compute the numerical integral of a given function.
# Implement the trapezoidal rule and Simpson's rule for integration.

In [54]:
def f(x):
    return np.sin(x)

In [55]:

# trapezoidal rule function
def trapezoidal_rule(f, a, b, n):
    x = np.linspace(a, b, n + 1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral

# Simpson's rule function
def simpsons_rule(f, a, b, n):
    if n % 2 == 1:
        raise ValueError("Number of intervals (n) must be even for Simpson's rule.")
    x = np.linspace(a, b, n + 1)
    y = f(x)
    h = (b - a) / n
    integral = (h / 3) * (y[0] + 4 * np.sum(y[1:n:2]) + 2 * np.sum(y[2:n-1:2]) + y[-1])
    return integral

In [56]:
# Example usage
a = 0  # Lower limit
b = np.pi  # Upper limit
n = 100  # Number of intervals

trapezoidal_result = trapezoidal_rule(f, a, b, n)
simpsons_result = simpsons_rule(f, a, b, n)

print("Trapezoidal Rule Result:", trapezoidal_result)
print("Simpson's Rule Result:", simpsons_result)

# Exact integral of sin(x) from 0 to pi is 2
exact_result = 2
print("Exact Result:", exact_result)

Trapezoidal Rule Result: 1.9998355038874436
Simpson's Rule Result: 2.000000010824504
Exact Result: 2


### 3. Partial Derivatives

In [64]:
# Calculate partial derivatives of multivariable functions using NumPy.
# Verify results by comparing with analytical solutions.

In [65]:
import sympy as sp

In [66]:
x, y = sp.symbols('x y')

f_sym = x**2 + y**2

In [61]:
# partial derivatives
partial_x_sym = sp.diff(f_sym, x)
partial_y_sym = sp.diff(f_sym, y)

print(f"Partial Derivative w.r.t x: {partial_x_sym}")
print(f"Partial Derivative w.r.t y: {partial_y_sym}")

Partial Derivative w.r.t x: 2*x
Partial Derivative w.r.t y: 2*y


In [68]:
def f(x, y):
    return x**2 + y**2

# Numerical partial derivative using central difference
def partial_derivative_x(f, x, y, h=1e-5):
    return (f(x + h, y) - f(x - h, y)) / (2 * h)

def partial_derivative_y(f, x, y, h=1e-5):
    return (f(x, y + h) - f(x, y - h)) / (2 * h)

In [69]:
# point to evaluate the derivatives
x0 = 2.0
y0 = 3.0

# numerical partial derivatives
numerical_derivative_x = partial_derivative_x(f, x0, y0)
numerical_derivative_y = partial_derivative_y(f, x0, y0)

# analytical derivatives
analytical_derivative_x = partial_x_sym.evalf(subs={x: x0, y: y0})
analytical_derivative_y = partial_y_sym.evalf(subs={x: x0, y: y0})

print(f"Numerical Partial Derivative w.r.t x at ({x0}, {y0}): {numerical_derivative_x}")
print(f"Analytical Partial Derivative w.r.t x at ({x0}, {y0}): {analytical_derivative_x}")

print(f"Numerical Partial Derivative w.r.t y at ({x0}, {y0}): {numerical_derivative_y}")
print(f"Analytical Partial Derivative w.r.t y at ({x0}, {y0}): {analytical_derivative_y}")

Numerical Partial Derivative w.r.t x at (2.0, 3.0): 4.000000000026205
Analytical Partial Derivative w.r.t x at (2.0, 3.0): 4.00000000000000
Numerical Partial Derivative w.r.t y at (2.0, 3.0): 6.000000000039306
Analytical Partial Derivative w.r.t y at (2.0, 3.0): 6.00000000000000


### 4. Optimization

In [71]:
# Use NumPy to solve optimization problems with constraints.

from scipy.optimize import minimize

# Define the objective function
def objective_function(vars):
    x, y = vars
    return (x - 1)**2 + (y - 2)**2

# Define the constraints
constraints = [
    {'type': 'ineq', 'fun': lambda vars: vars[0] + vars[1] - 1},  # x + y >= 1
    {'type': 'ineq', 'fun': lambda vars: 2 - (vars[0] - vars[1])},  # x - y <= 2
    {'type': 'ineq', 'fun': lambda vars: vars[0]},  # x >= 0
    {'type': 'ineq', 'fun': lambda vars: vars[1]},  # y >= 0
]

# Initial guess
initial_guess = [0.5, 0.5]

# Perform the optimization
result = minimize(objective_function, initial_guess, constraints=constraints)

# Print the results
if result.success:
    optimized_x, optimized_y = result.x
    print(f"Optimal solution found: x = {optimized_x}, y = {optimized_y}")
    print(f"Minimum value of the objective function: {result.fun}")
else:
    print("Optimization failed:", result.message)

Optimal solution found: x = 1.0, y = 2.0
Minimum value of the objective function: 0.0
