### Task 10: Introduction to NumPy (arrays, basic operations)
### Submitted by: Awais Anwer

In [1]:
# Create a 1D NumPy array containing the integers from 0 to 9.
# Create a 2D NumPy array (3x3) containing random integers between 1 and 20.
# Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.
# Add two 1D arrays element-wise.
# Multiply two 2D arrays element-wise.
# Calculate the dot product of two matrices.
# Calculate the mean, median, and standard deviation of a 1D array.
# Find the maximum and minimum values in a 2D array.
# Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.
# Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.
# Calculate the cumulative sum of a 1D array.
# Compute the correlation coefficient matrix of a 2D array.
# Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.


In [2]:
import numpy as np

In [3]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a2 = np.random.randint(1, 20, size=(3, 3))
a2

array([[ 8, 10,  5],
       [12,  1,  1],
       [10,  7, 19]])

In [5]:
a3 = np.ones(((2, 3, 4)))
a3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
# Add two 1D arrays element-wise.
arr1 = np.array([1, 2, 1])
arr2 = np.array([4, 2, 4])
arr1 + arr2

array([5, 4, 5])

In [9]:
# Multiply two 2D arrays element-wise.
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
print(arr1 * arr2)

[[ 5 12]
 [21 32]]


In [10]:
# Calculate the dot product of two matrices.
np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

In [13]:
# Calculate the mean, median, and standard deviation of a 1D array.
arr1 = np.array([2, 4, 5, 10, 15, 20, 21, 24, 30, 35])
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))

16.6
17.5
10.753604047016053


In [15]:
# Find the maximum and minimum values in a 2D array.
np.random.seed(42)
arr = np.random.randint(100, size=(3, 4))
print(arr)
print(np.max(arr))
print(np.min(arr))

[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]]
99
14


In [16]:
# Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.
arr = np.random.normal(0, 1, 1000)
print(arr)

[ 3.92579750e-01 -9.29184667e-01  7.98318122e-02 -1.59516502e-01
  2.22218266e-02 -4.27792914e-01 -5.31817410e-01 -1.17475502e-01
  2.22078902e-01 -7.67976502e-01  1.42464602e-01 -3.46521842e-02
  1.13433927e+00 -1.04745548e-01 -5.25122851e-01  1.91277127e+00
 -2.02671962e+00  1.11942361e+00  7.79192635e-01 -1.10109776e+00
  1.13022819e+00  3.73118915e-01 -3.86472951e-01 -1.15877024e+00
  5.66112827e-01 -7.04453450e-01 -1.37793930e+00 -3.53116652e-01
 -4.61465718e-01  6.66572785e-02 -1.76285662e-01  1.20089277e+00
  6.98398941e-01 -1.71628835e-01 -9.07186580e-01  1.18862573e+00
  7.85532124e-01  2.65601009e+00  2.63486040e-01  1.64177112e+00
  4.60816300e-01  8.59234716e-02 -1.50995728e+00  7.21502462e-01
 -8.43419923e-01 -5.13325405e-01 -4.35368025e-02 -2.75300910e-01
 -1.56306679e+00 -7.95630992e-01  9.30584401e-01  6.77767410e-01
  6.98440259e-01  1.73602064e-01  6.62284514e-01  2.41122163e-01
 -1.68205088e-01  1.16476865e+00 -2.45747687e-01 -7.69667774e-01
  1.21217234e+00  1.23349

In [19]:
# Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.

arr = np.random.randint(10, 50, size=(5, 5))
print(arr)

[[12 15 18 15 18]
 [48 40 41 21 17]
 [17 37 29 16 20]
 [29 25 13 15 31]
 [35 12 23 20 27]]


In [21]:
# Calculate the cumulative sum of a 1D array.
arr = np.random.randint(10, size=15)
print(arr)
print(np.cumsum(arr))

[2 6 3 7 6 4 6 2 1 5 1 2 5 4 7]
[ 2  8 11 18 24 28 34 36 37 42 43 45 50 54 61]


In [23]:
# Compute the correlation coefficient matrix of a 2D array.
arr = np.random.randint(0, 10, size=(5, 5))
print("matrix:")
print(arr)
print("correlation coefficient matrix:")
print(np.corrcoef(arr))

matrix:
[[3 1 1 3 5]
 [6 9 2 2 9]
 [5 2 1 7 4]
 [0 2 9 7 3]
 [6 9 1 6 4]]
correlation coefficient matrix:
[[ 1.          0.30671918  0.60075141 -0.306771   -0.08104409]
 [ 0.30671918  1.         -0.1910865  -0.78190358  0.51717985]
 [ 0.60075141 -0.1910865   1.         -0.16408553  0.29110979]
 [-0.306771   -0.78190358 -0.16408553  1.         -0.64575713]
 [-0.08104409  0.51717985  0.29110979 -0.64575713  1.        ]]


In [24]:
# Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.
rolling = np.random.randint(1, 7, 1000)
print(np.unique(rolling, return_counts=True))

(array([1, 2, 3, 4, 5, 6]), array([160, 171, 137, 183, 180, 169]))
